package com.example.customdartgames;

import com.example.customdartgames.model.Game;
import com.example.customdartgames.model.User;
import com.example.customdartgames.model.UserGameStats;
import com.example.customdartgames.model.UserGameStatsId;
import com.example.customdartgames.repository.GameRepository;
import com.example.customdartgames.repository.UserGameStatsRepository;
import com.example.customdartgames.repository.UserRepository;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

@Controller
@RequestMapping(path = "/dart") // URLs start with .../dart
public class MainController {

	public static final int CRICKET_CODE = 1;
	public static final int CRICKET_HONOR_CODE = 2;
	public static final int FIVE_OH_ONE_CODE = 3;
	public static final int THREE_OH_ONE_CODE = 4;
	public static final int ONE_OH_ONE_CODE = 5;
	public static final int SCRAM_CODE = 6;
	public static final int SCRAM_2P_CODE = 7;
	public static final int SCRAM_3P_CODE = 8;
	public static final int OZONE_CODE = 9; // TODO different ozone based on players (3 and 2, max 4)
	public static final int BASEBALL_CODE = 10;
	public static final int BALLBASE_CODE = 11;
	public static final int CLOCK_CODE = 12;
	public static final int FAST_CLOCK_CODE = 13;
	public static final int GEO_JURA_CODE = 14;
	public static final int PURPLE_STAIN_CODE = 15;
	public static final int KILLER_CODE = 16;

	@Autowired // This means to get the bean called userRepository auto-generated by Spring
	private UserRepository userRepository;

	@Autowired
	private GameRepository gameRepository;

	@Autowired
	private UserGameStatsRepository userGameStatsRepository;

	@GetMapping(path = "/")
	public String home() {
		return "home";
	}

	@GetMapping(path = "/players")
	public String players(Model model) { // model is the spring mvc's way to pass data from controller to view.
		List<Game> games = gameRepository.findAll();
		List<User> users = userRepository.findAll();
		List<UserGameStats> stats = userGameStatsRepository.findAll();

		Map<Integer, Map<Integer, UserGameStats>> statsByUserAndGame = new HashMap<>(); // (User id,(Game id,
																						// UserGameStats)
		Map<Integer, Integer> bestPerGame = new HashMap<>(); // GameId

		for (UserGameStats stat : stats) {
			statsByUserAndGame.computeIfAbsent(stat.getUser().getId(), id -> new HashMap<>()) // create a map with
																								// UserId, (GameId,
																								// UserGameStats score)
					.put(stat.getGame().getId(), stat); // populate

			Integer bestScore = stat.getBestScore(); // In every game, look for the best score registered
			if (bestScore != null) {
				Integer gameId = stat.getGame().getId();
				Integer currentBest = bestPerGame.get(gameId);
				if (currentBest == null || bestScore > currentBest) {
					bestPerGame.put(gameId, bestScore);
				}
			}
		}

		model.addAttribute("games", games);
		model.addAttribute("users", users);
		model.addAttribute("statsByUserAndGame", statsByUserAndGame);
		model.addAttribute("bestPerGame", bestPerGame);
		return "players";
	}

	@GetMapping(path = "/players/new")
	public String newPlayerForm() {
		return "player-form";
	}

	@PostMapping(path = "/add")
	public String addPlayer(@RequestParam String username) {

		if (userRepository.findByUsername(username) == null) {
			String formattedUsername = (StringUtils.capitalize(username.toLowerCase())).trim();
			User user = new User();
			user.setUsername(formattedUsername);
			userRepository.save(user);
		}

		return "redirect:/dart/players";
	}

	@GetMapping(path = "/play")
	public String play(Model model) {
		List<Game> games = gameRepository.findAll();

		model.addAttribute("games", games);
		return "play";
	}

	@PostMapping(path = "/play/start")
	public String playStart(@RequestParam Integer gameId) {

		Integer playerNumber = switch (gameId) {
		case SCRAM_CODE -> 2;
		case SCRAM_3P_CODE -> 3;
		default -> 4;
		};

		// TODO ozone = 4 players, ozone 3 players, ozone 2 players

		// redirect on player set up.
		return "redirect:/dart/play/players-setup?gameId=" + gameId + "&playerNumber=" + playerNumber;
	}

	@GetMapping(path = "/play/players-setup")
	public String playersSetup(@RequestParam("gameId") Integer gameId,
			@RequestParam("playerNumber") Integer playerNumber, Model model) {
		List<User> user = userRepository.findAll();

		// TODO secured parameters

		// Because it's optional, need to be wrapped as an object Game
		gameRepository.findById(gameId).ifPresent(game -> model.addAttribute("game", game));
		model.addAttribute("users", user);
		model.addAttribute("playerNumber", playerNumber);
		return "players-setup";
	}

	@PostMapping(path = "/play/start-game")
	public String startGame(@RequestParam("gameId") Integer gameId,
			@RequestParam("orderedPlayerIds") List<String> orderedPlayerIds, Model model) {

		Game game = gameRepository.findById(gameId).orElseThrow();

		List<User> players = new java.util.ArrayList<>(List.of());

		for (String playerId : orderedPlayerIds) {
			int realPlayerId = Integer.parseInt(playerId.trim());
			userRepository.findById(realPlayerId).ifPresent(players::add); // wrapper because optional

		}

		if ((FIVE_OH_ONE_CODE >= gameId) || (gameId <= ONE_OH_ONE_CODE)) {
			int startingScore = switch (gameId) {
			case FIVE_OH_ONE_CODE -> 501;
			case THREE_OH_ONE_CODE -> 301;
			default -> 101;
			};

			model.addAttribute("startingScore", startingScore);
			model.addAttribute("game", game);
			model.addAttribute("players", players);

			return "game-countdown";
		}
		return "";
	}

	@PostMapping(path = "/play/finish-countdown")
	public String finishGame(@RequestParam("gameId") Integer gameId, @RequestParam("userId") Integer userId,
			@RequestParam("turns") Integer turns) {

		UserGameStatsId userGameStatsId = new UserGameStatsId(userId, gameId); // Register an id with winner info

		// If no stat line for this player and this game :
		if (userGameStatsRepository.findById(userGameStatsId).isEmpty()) {
			UserGameStats userGameStats = new UserGameStats();
			userGameStats.setId(userGameStatsId);
			userGameStats.setUser(userRepository.findById(userId).orElseThrow());
			userGameStats.setGame(gameRepository.findById(gameId).orElseThrow());
			userGameStats.setBestScore(turns);
			userGameStatsRepository.save(userGameStats);
		} else { // else fetch the current best score and compare the best one
			userGameStatsRepository.findById(userGameStatsId).ifPresent(userGameStats -> {
				if (userGameStats.getBestScore() > turns) {
					userGameStats.setBestScore(turns);
					userGameStatsRepository.save(userGameStats);
				}
			});
		}

		return "redirect:/dart/play";
	}

}
