package com.example.customdartgames;

import com.example.customdartgames.model.Game;
import com.example.customdartgames.model.User;
import com.example.customdartgames.model.UserGameStats;
import com.example.customdartgames.model.UserGameStatsId;
import com.example.customdartgames.repository.GameRepository;
import com.example.customdartgames.repository.UserGameStatsRepository;
import com.example.customdartgames.repository.UserRepository;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.example.customdartgames.util.Util;

import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

@Controller
@RequestMapping(path = "/dart") // URLs start with .../dart
public class MainController {

	public static final int CRICKET_CODE = 1;
	public static final int CRICKET_HONOR_CODE = 2;
	public static final int FIVE_OH_ONE_CODE = 3;
	public static final int THREE_OH_ONE_CODE = 4;
	public static final int ONE_OH_ONE_CODE = 5;
	public static final int SCRAM_CODE = 6;
	public static final int SCRAM_4P_CODE = 7;
	public static final int SCRAM_3P_CODE = 8;
	public static final int OZONE_CODE = 9;
	public static final int OZONE_3P_CODE = 10;
	public static final int BASEBALL_CODE = 11;
	public static final int BALLBASE_CODE = 12;
	public static final int CLOCK_CODE = 13;
	public static final int FAST_CLOCK_CODE = 14;
	public static final int GEO_JURA_CODE = 15;
	public static final int PURPLE_STAIN_CODE = 16;
	public static final int KILLER_CODE = 17;

	public static final int ZERO_PLAYER = 0;
	public static final int TWO_PLAYERS = 2;
	public static final int THREE_PLAYERS = 3;
	public static final int FOUR_PLAYERS = 4;
	public static final int SIX_PLAYERS = 6;
	public static final int TEN_PLAYERS = 10;

	public static final String VARIANT = "variant";

	@Autowired // This means to get the bean called userRepository auto-generated by Spring
	private UserRepository userRepository;

	@Autowired
	private GameRepository gameRepository;

	@Autowired
	private UserGameStatsRepository userGameStatsRepository;

	@GetMapping(path = "/")
	public String home() {
		return "home";
	}

	@GetMapping(path = "/rules")
	public String rules(Model model) {
		model.addAttribute("games", gameRepository.findAll());
		return "rules";
	}

	@GetMapping(path = "/players")
	public String players(Model model) { // model is the spring mvc's way to pass data from controller to view.
		List<Game> games = gameRepository.findAll();
		List<User> users = userRepository.findAll();
		List<UserGameStats> stats = userGameStatsRepository.findAllWithUserAndGame();

		Map<Integer, Map<Integer, UserGameStats>> statsByUserAndGame = new HashMap<>(); // (User id,(Game id,
																						// UserGameStats)
		Map<Integer, Integer> bestPerGame = new HashMap<>(); // Game id, bestScore

		for (UserGameStats stat : stats) {

			Game game = stat.getGame();
			// create a map with UserId, (GameId,UserGameStats score)
			statsByUserAndGame.computeIfAbsent(stat.getUser().getId(), id -> new HashMap<>()).put(game.getId(), stat); // populate

			Integer bestScore = stat.getBestScore(); // In every game, look for the best score registered
			if (bestScore != null) {
				Integer gameId = game.getId();
				Integer currentBest = bestPerGame.get(gameId);
				boolean isBasedOnTurnGame = game.isScoreBasedOnTurn();

				// If it's not a turn based game, store the highest score
				if (currentBest == null || ((bestScore > currentBest) && !isBasedOnTurnGame)) {
					bestPerGame.put(gameId, bestScore);
				}

				// If it's a turn based game, store the lowest result number
				else if ((bestScore < currentBest) && isBasedOnTurnGame) {
					bestPerGame.put(gameId, bestScore);
				}
			}
		}

		model.addAttribute("games", games);
		model.addAttribute("users", users);
		model.addAttribute("statsByUserAndGame", statsByUserAndGame);
		model.addAttribute("bestPerGame", bestPerGame);
		return "players";
	}

	@GetMapping(path = "/players/new")
	public String newPlayerForm() {
		return "player-form";
	}

	@PostMapping(path = "/add")
	public String addPlayer(@RequestParam String username) {

		if (userRepository.findByUsername(username) == null) {
			String formattedUsername = (StringUtils.capitalize(username.toLowerCase())).trim();
			User user = new User();
			user.setUsername(formattedUsername);
			userRepository.save(user);
		}

		return "redirect:/dart/players";
	}

	@GetMapping(path = "/play")
	public String play(Model model) {
		List<Game> games = gameRepository.findAll();

		model.addAttribute("games", games);
		return "play";
	}

	@PostMapping(path = "/play/start")
	public String playStart(@RequestParam Integer gameId, Model model) {

		// Set the playerNumber based on the game code
		Integer playerNumber = switch (gameId) {
		case CRICKET_CODE, CRICKET_HONOR_CODE, PURPLE_STAIN_CODE, KILLER_CODE, OZONE_3P_CODE -> SIX_PLAYERS;
		case FIVE_OH_ONE_CODE, THREE_OH_ONE_CODE, ONE_OH_ONE_CODE, BASEBALL_CODE, BALLBASE_CODE, CLOCK_CODE,
				FAST_CLOCK_CODE, GEO_JURA_CODE ->
			TEN_PLAYERS;
		case SCRAM_CODE, OZONE_CODE -> TWO_PLAYERS;
		case SCRAM_3P_CODE -> THREE_PLAYERS;
		default -> FOUR_PLAYERS;
		};

		// redirect on player set up.
		return "redirect:/dart/play/players-setup?gameId=" + gameId + "&playerNumber=" + playerNumber;
	}

	@GetMapping(path = "/play/players-setup")
	public String playersSetup(@RequestParam("gameId") Integer gameId,
			@RequestParam("playerNumber") Integer playerNumber, Model model) {
		List<User> user = userRepository.findAll();
		String redirectionUrl = "redirect:/dart/play/players-setup?gameId=" + gameId + "&playerNumber=";

		// Secured parameters
		switch (gameId) {
		// if playerNumber > 6 or playerNumber < 1
		case CRICKET_CODE, CRICKET_HONOR_CODE, PURPLE_STAIN_CODE, KILLER_CODE, OZONE_3P_CODE -> {
			if (playerNumber > SIX_PLAYERS || playerNumber < ZERO_PLAYER) {
				return redirectionUrl + SIX_PLAYERS; // redirect to 6 players
			}
		}
		case FIVE_OH_ONE_CODE, THREE_OH_ONE_CODE, ONE_OH_ONE_CODE, BASEBALL_CODE, BALLBASE_CODE, CLOCK_CODE,
				FAST_CLOCK_CODE, GEO_JURA_CODE -> {
			if (playerNumber > TEN_PLAYERS || playerNumber < ZERO_PLAYER) {
				return redirectionUrl + TEN_PLAYERS; // redirect to 10 players
			}
		}
		case SCRAM_CODE, OZONE_CODE -> {
			if (playerNumber != TWO_PLAYERS) {
				return redirectionUrl + TWO_PLAYERS; // redirect to 2 players
			}
		}
		case SCRAM_3P_CODE -> {
			model.addAttribute("stopperCount", 1);
			if (playerNumber != THREE_PLAYERS) {
				return redirectionUrl + THREE_PLAYERS; // redirect to 3 players
			}
		}
		case SCRAM_4P_CODE -> {
			model.addAttribute("stopperCount", 2);
			if (playerNumber != FOUR_PLAYERS) {
				return redirectionUrl + FOUR_PLAYERS; // redirect to 4 players
			}
		}
		default -> {
			return "redirect:/dart/play";
		}
		}

		// Because it's optional, need to be wrapped as an object Game
		gameRepository.findById(gameId).ifPresent(game -> model.addAttribute("game", game));
		model.addAttribute("users", user);
		model.addAttribute("playerNumber", playerNumber);
		return "players-setup";
	}

	@PostMapping(path = "/play/start-game")
	public String startGame(@RequestParam("gameId") Integer gameId,
			@RequestParam("orderedPlayerIds") List<String> orderedPlayerIds, Model model) {

		Game game = gameRepository.findById(gameId).orElseThrow();

		List<User> players = new java.util.ArrayList<>(List.of());

		for (String playerId : orderedPlayerIds) {
			int realPlayerId = Integer.parseInt(playerId.trim());
			userRepository.findById(realPlayerId).ifPresent(players::add); // wrapper because optional
		}

		model.addAttribute("game", game);
		model.addAttribute("players", players);

		switch (gameId) {
		case CRICKET_CODE -> {
			model.addAttribute(VARIANT, "cricket");
			return "game-cricket";
		}
		case CRICKET_HONOR_CODE -> {
			model.addAttribute(VARIANT, "cricket-honor");
			return "game-cricket";
		}

		case FIVE_OH_ONE_CODE, THREE_OH_ONE_CODE, ONE_OH_ONE_CODE -> {
			int startingScore = switch (gameId) {
			case FIVE_OH_ONE_CODE -> 501;
			case THREE_OH_ONE_CODE -> 301;
			default -> 101;
			};
			model.addAttribute("startingScore", startingScore);
			return "game-countdown";
		}
		case SCRAM_CODE -> {
			model.addAttribute(VARIANT, "scram");
			return "game-scram";
		}
		case SCRAM_4P_CODE -> {
			model.addAttribute(VARIANT, "scram-2v2");
			return "game-scram";
		}
		case SCRAM_3P_CODE -> {
			model.addAttribute(VARIANT, "scram-2v1");
			return "game-scram";
		}
		case OZONE_CODE -> {
			// TODO
		}
		case BASEBALL_CODE -> {
			model.addAttribute(VARIANT, "baseball");
			return "game-baseball";
		}
		case BALLBASE_CODE -> {
			model.addAttribute(VARIANT, "ballbase");
			return "game-baseball";
		}
		case CLOCK_CODE -> {
			return "game-clock";
		}
		case FAST_CLOCK_CODE -> {
			model.addAttribute(VARIANT, "fast-clock");
			return "game-clock";
		}
		case PURPLE_STAIN_CODE -> {
			return "game-purple-stain";
		}
		}
		return "redirect:/dart/play";
	}

	@PostMapping(path = "/play/finish")
	public String finishGame(@RequestParam("gameId") Integer gameId, @RequestParam("userId") Integer userId,
			@RequestParam("result") Integer result) {

		UserGameStatsId userGameStatsId = new UserGameStatsId(userId, gameId); // Register an id with winner info
		Game game = gameRepository.findById(gameId).orElseThrow();
		boolean isBasedOnTurn = game.isScoreBasedOnTurn();

		// If no stat line for this player and this game :
		if (userGameStatsRepository.findById(userGameStatsId).isEmpty()) {
			UserGameStats userGameStats = new UserGameStats();
			userGameStats.setId(userGameStatsId);
			userGameStats.setUser(userRepository.findById(userId).orElseThrow());
			userGameStats.setGame(game);
			userGameStats.setBestScore(result);
			userGameStatsRepository.save(userGameStats);
		} else {
			// else fetch the current best score and compare the best one / and worst too
			userGameStatsRepository.findById(userGameStatsId).ifPresent(userGameStats -> {

				// Compute the worst/best score
				Util.saveScoresToStats(userGameStats, result, isBasedOnTurn);

				// Save data
				userGameStatsRepository.save(userGameStats);
			});
		}

		return "redirect:/dart/play";
	}

}
