package com.example.customdartgames;

import com.example.customdartgames.model.User;
import com.example.customdartgames.repository.GameRepository;
import com.example.customdartgames.repository.UserGameStatsRepository;
import com.example.customdartgames.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
@RequestMapping(path="/dart") //  URLs start with .../dart
public class MainController {
	@Autowired // This means to get the bean called userRepository auto-generated by Spring
	private UserRepository userRepository;
    @Autowired
    private GameRepository gameRepository;
    @Autowired
    private UserGameStatsRepository userGameStatsRepository;



	@PostMapping(path="/add") //  POST Requests
	@ResponseBody // the returned String is the response body, not a view name
	public  String addNewUser (@RequestParam String username){
		// @RequestParam means it is a parameter
		User n = new User();
		n.setUsername(username);
		userRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/")
	public String home(Model model) { //model is the spring mvc's way to pass data from controller to view.
		// no @ResponseBody here: the returned String is resolved as a Thymeleaf view name
		model.addAttribute("message", "Welcome to Custom Dart Games!");
		return "home";
	}
}
